apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.client.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.services.client.name }}
    {{- include "learning-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.client.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.client.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.client.name }}
    spec:
      containers:
        - name: {{ .Values.services.client.name }}
          image: {{ .Values.common.registry }}/{{ .Values.services.client.image }}:{{ .Values.services.client.tag }}
          imagePullPolicy: {{ .Values.common.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.client.targetPort }}
          {{- if and .Values.services.client.secrets (eq .Values.services.client.secrets.enabled true) }}
          envFrom:
            - secretRef:
                name: {{ .Values.services.client.name }}-secrets
          {{- end }}
          resources:
            {{- toYaml .Values.services.client.resources | nindent 12 }}