replicaCount: 1

image:
  repository: enrollment.azurecr.io/enrollment-api
  tag: 
  pullPolicy: IfNotPresent

service:
  protocol: TCP
  port: 80
  targetPort: 80
  nodePort: 31080
  type: LoadBalancer

pod:
  containerPort: 3000

namespace: enrollment

configmap:
  enabled: true
  name: enrollment-configmap
  data:
    MAIN_DB_NAME: main

secrets:
  enabled: true
  name: enrollment-secrets
  data:  
    AZURE_STORAGE_CONNECTION_STRING: ""
    