replicaCount: 1

image:
  repository: payment.azurecr.io/payment-api
  tag: 
  pullPolicy: IfNotPresent

service:
  protocol: TCP
  port: 80
  targetPort: 80
  nodePort: 31080
  type: LoadBalancer

pod:
  containerPort: 3000

namespace: payment

configmap:
  enabled: true
  name: payment-configmap
  data:
    MAIN_DB_NAME: main

secrets:
  enabled: true
  name: payment-secrets
  data:  
    AZURE_STORAGE_CONNECTION_STRING: ""
    