apiVersion: v1
kind: Service
metadata:
  name: apigateway-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: apigateway
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.pod.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigateway-app-gateway
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
  - hosts:
    - apigatewayapik8s.eastus.cloudapp.azure.com
    secretName: tls-secret-apigatewayapik8s
  rules:
  - host: apigatewayapik8s.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: apigateway-api-service
            port:
              number: {{ .Values.service.targetPort }}
        pathType: Prefix
