apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.pod.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
            - secretRef:
                name: {{ .Values.secrets.name }}
