{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: "{{ $value | toString | b64enc }}"
{{- end }}
{{- end }}
