{{- range $service, $config := .Values.services }}
{{- if and $config.secrets (eq $config.secrets.enabled true) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $config.name | lower }}-secrets
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $config.name }}
    {{- include "learning-platform.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $config.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
