name: Continuous Deployment

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Docker
    strategy:
      matrix:
        service: [
          {name: 'user-management', dir: './UserManagementService'},
          {name: 'course-management', dir: './CourseManagementService'},
          {name: 'payment-management', dir: './PaymentManagementService'},
          {name: 'enrollment-management', dir: './EnrollmentManagementService'}
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "env=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}}" == "refs/heads/main" ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "env=development" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update Dockerfile for native module support
        working-directory: ${{ matrix.service.dir }}
        run: |
          if [ -f "Dockerfile" ]; then
            sed -i '/^FROM/a RUN apk add --no-cache python3 make g++ gcc libc-dev' Dockerfile
          else
            echo "Dockerfile not found in ${{ matrix.service.dir }}"
            exit 1
          fi

      - name: Build and push multi-arch Docker images
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service.dir }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NPM_CONFIG_OPTIONAL=false

      - name: Create kubeconfig file
        run: |
          if [[ "${{ steps.env.outputs.env }}" == "production" ]]; then
            echo -n "${{ secrets.PROD_KUBE_CONFIG }}" | base64 --decode > kubeconfig
          else
            echo -n "${{ secrets.DEV_KUBE_CONFIG }}" | base64 --decode > kubeconfig
          fi

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Deploy service using Helm
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          cat > values-runtime.yaml <<EOF
          namespace: default
          common:
            registry: ${{ secrets.DOCKERHUB_USERNAME }}
            imagePullPolicy: Always
            environment: ${{ steps.env.outputs.env }}
          services:
            ${MATRIX_NAME}:
              tag: ${{ github.sha }}
              enabled: true
          EOF

          helm upgrade --install learning-platform ./learning-platform \
            --namespace default \
            --values learning-platform/values.yaml \
            --values values-runtime.yaml
