name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches: [main, develop]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  deploy:
    if: |
      (github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Determine environment
      id: env
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          ENVIRONMENT="${{ github.event.inputs.environment }}"
        elif [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
          ENVIRONMENT="production"
        else
          ENVIRONMENT="development"
        fi
        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
        echo "namespace=$ENVIRONMENT" >> $GITHUB_OUTPUT
        if [[ "$ENVIRONMENT" == "production" ]]; then
          echo "values_suffix=prod" >> $GITHUB_OUTPUT
        else
          echo "values_suffix=dev" >> $GITHUB_OUTPUT
        fi

    - name: Set Kubeconfig Secret Value
      id: kubeconfig
      run: |
        if [[ "${{ steps.env.outputs.environment }}" == "production" ]]; then
          echo "value=${{ secrets.PROD_KUBE_CONFIG }}" >> $GITHUB_OUTPUT
        else
          echo "value=${{ secrets.DEV_KUBE_CONFIG }}" >> $GITHUB_OUTPUT
        fi

    - name: Decode kubeconfig
      run: |
        echo "${{ steps.kubeconfig.outputs.value }}" | base64 -d > kubeconfig

    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ github.workspace }}/kubeconfig

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Get SHA
      id: vars
      run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      env:
        GITHUB_SHA: ${{ github.event.workflow_run.head_sha || github.sha }}

    - name: Generate values-runtime.yaml
      run: |
        cat > values-runtime.yaml << EOF
        namespace: ${{ steps.env.outputs.namespace }}
        common:
          registry: ${{ secrets.DOCKERHUB_USERNAME }}
          imagePullPolicy: Always
          environment: ${{ steps.env.outputs.environment }}
        services:
          client:
            tag: ${{ steps.vars.outputs.sha }}
            enabled: true
            secrets:
              enabled: true
              data:
                REACT_APP_BACKEND_URL: "${{ secrets.REACT_APP_BACKEND_URL }}"
                REACT_APP_EMAILJS_SERVICE_ID: "${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}"
                REACT_APP_EMAILJS_TEMPLATE_ID: "${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}"
                REACT_APP_EMAILJS_USER_ID: "${{ secrets.REACT_APP_EMAILJS_USER_ID }}"
                REACT_APP_FIREBASE_API_KEY: "${{ secrets.REACT_APP_FIREBASE_API_KEY }}"
                REACT_APP_FIREBASE_APP_ID: "${{ secrets.REACT_APP_FIREBASE_APP_ID }}"
                REACT_APP_FIREBASE_AUTH_DOMAIN: "${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}"
                REACT_APP_FIREBASE_MEASUREMENT_ID: "${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}"
                REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}"
                REACT_APP_FIREBASE_PROJECT_ID: "${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}"
                REACT_APP_FIREBASE_STORAGE_BUCKET: "${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}"
          apiGateway:
            tag: ${{ steps.vars.outputs.sha }}
            enabled: true
            secrets:
              enabled: true
              data:
                MONGODB_URL: "${{ secrets.MONGODB_URL }}"
          userManagement:
            tag: ${{ steps.vars.outputs.sha }}
            enabled: true
            secrets:
              enabled: true
              data:
                MONGODB_URL: "${{ secrets.MONGODB_URL }}"
          courseManagement:
            tag: ${{ steps.vars.outputs.sha }}
            enabled: true
            secrets:
              enabled: true
              data:
                MONGODB_URL: "${{ secrets.MONGODB_URL }}"
          paymentManagement:
            tag: ${{ steps.vars.outputs.sha }}
            enabled: true
            secrets:
              enabled: true
              data:
                MONGODB_URL: "${{ secrets.MONGODB_URL }}"
          enrollmentManagement:
            tag: ${{ steps.vars.outputs.sha }}
            enabled: true
            secrets:
              enabled: true
              data:
                MONGODB_URL: "${{ secrets.MONGODB_URL }}"
        EOF

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install learning-platform ./learning-platform \
          --namespace ${{ steps.env.outputs.namespace }} \
          --create-namespace \
          --values ./learning-platform/values.yaml \
          --values ./learning-platform/values-${{ steps.env.outputs.values_suffix }}.yaml \
          --values values-runtime.yaml
