name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches: [main, develop]
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  deploy-to-development:
    if: |
      (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development')
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
      
    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.DEV_KUBE_CONFIG }}
    
    - name: Update Kubernetes manifests
      run: |
        # Get the SHA from the CI workflow that triggered this one
        GITHUB_SHA=${{ github.event.workflow_run.head_sha || github.sha }}
        
        # Update image tags in all manifest files
        for service in client api-gateway user-management course-management payment-management enrollment-management; do
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/${service}:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${service}:${GITHUB_SHA}|g" k8s/dev/*.yaml
        done
    
    - name: Deploy to Kubernetes Dev Environment
      run: |
        kubectl apply -f k8s/dev/
        kubectl get pods -n development

  deploy-to-production:
    if: |
      (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
      
    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.PROD_KUBE_CONFIG }}
    
    - name: Update Kubernetes manifests
      run: |
        # Get the SHA from the CI workflow that triggered this one
        GITHUB_SHA=${{ github.event.workflow_run.head_sha || github.sha }}
        
        # Update image tags in all manifest files
        for service in client api-gateway user-management course-management payment-management enrollment-management; do
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/${service}:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${service}:${GITHUB_SHA}|g" k8s/prod/*.yaml
        done
    
    - name: Deploy to Kubernetes Production Environment
      run: |
        kubectl apply -f k8s/prod/
        kubectl get pods -n production