# Default values for learning-platform
namespace:

# Common configurations
common:
  registry: manulagunatilleke
  imagePullPolicy: Always
  environment: development

# Domain configuration
domain: akslerningplatform.eastus.cloudapp.azure.com

ingress:
  enabled: true
  className: webapprouting.kubernetes.azure.com  # or nginx, or whatever your ingress class is
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

# Microservices configuration
services:
  userManagement:
    name: user-management
    image: user-management
    tag: latest
    port: 80
    targetPort: 3001
    path: /user(/|$)(.*)
    replicas: 1
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    secrets:
      enabled: true
      data:
        MONGODB_URL: ""
        JWT_SECRET: "your_fallback_secret"
        SESSION_SECRET: "Your_Secret_Token"
        NODE_ENV: "production"

  courseManagement:
    name: course-management
    image: course-management
    tag: latest
    port: 80
    targetPort: 3002
    path: /course(/|$)(.*)
    replicas: 1
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    secrets:
      enabled: true
      data:
        MONGODB_URL: ""
        
  paymentManagement:
    name: payment-management
    image: payment-management
    tag: latest
    port: 80
    targetPort: 3003
    path: /payment(/|$)(.*)
    replicas: 1
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    secrets:
      enabled: true
      data:
        MONGODB_URL: ""
        
  enrollmentManagement:
    name: enrollment-management
    image: enrollment-management
    tag: latest
    port: 80
    targetPort: 3004
    path: /enrollment(/|$)(.*)
    replicas: 1
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    secrets:
      enabled: true
      data:
        MONGODB_URL: ""